config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :yoga_classes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :show]
  end

  resources :teachers, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studios, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studio_teachers, only: [:create]

  resources :bookings, only: [:index, :destroy]

  resources :reviews, only: [:destroy]
  # resources :bookings, only: [:show]

  # Path for confirmation page after the booking was successful
  get "bookings/:id/confirmation", to: "bookings#confirmation", as: :confirmation
  resources :yoga_classes, only: [:index, :show, :new, :create]
  get "/admin", to: "pages#admin"

  resources :users do
    # Add a custom route for the confirmation action if needed
    get 'confirmation', on: :member
  end
end

app/models/yoga_studio.rb
class YogaStudio < ApplicationRecord
  belongs_to :user
  has_many :reviews, as: :reviewable
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :yoga_studio_teachers, dependent: :destroy
  has_many :yoga_classes, through: :yoga_studio_teacher

  # validation
  validates :name, presence: true, length: { minimum: 3 }, uniqueness: { scope: :address }
  validates :address, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { in: 10..800 }
  # validate :photos_type

  # def photos_type
  #   if photos.attached? == false
  #     errors.add(:photos, ": at least one photo should be attached!")
  #   end
  # end
end

app/controllers/yoga_studios_controller.rb
class YogaStudiosController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def show
    @yoga_studio = YogaStudio.find(params[:id])
    @review = Review.new

    # Map markers
    @yoga_studios = [@yoga_studio]
    @markers = @yoga_studios.map do |yoga_studio|
      {
        lat: yoga_studio.latitude,
        lng: yoga_studio.longitude,
        info_window_html: render_to_string(partial: "shared/show_window", locals: { yoga_studio: yoga_studio }),
        marker_html: render_to_string(partial: "shared/marker")
      }
    end
  end

  def index
    @yoga_studios = YogaStudio.all
  end

  def new
    @yoga_studio = YogaStudio.new
  end

  def create
    @yoga_studio = YogaStudio.new(studio_params)
    @yoga_studio.user = current_user
    if @yoga_studio.save
      redirect_to yoga_studio_path(@yoga_studio)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    set
  end

  def update
    set
    if @yoga_studio.update(studio_params)
      redirect_to yoga_studio_path(@yoga_studio)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    set
    @yoga_studio.destroy
    redirect_to admin_path, status: :see_other
  end

  private

  def set
    @yoga_studio = YogaStudio.find(params[:id])
  end

  def studio_params
    params.require(:yoga_studio).permit(:name, :address, :description, photos: [])
  end
end

app/views/yoga_studios/_form.html.erb
<div class="form-control bg-white p-5 rounded-4 border-0 shadow-sm">
  <%= simple_form_for(@yoga_studio) do |ys| %>
    <strong><h3 class="mb-4">Create a yoga class</h3></strong>
    <%= ys.input :name %>
    <%= ys.input :description %>
    <%= ys.input :address %>
    <%= ys.input :photos, as: :file, input_html: {multiple: true} %>
    <div class="d-flex justify-content-between">
      <%= ys.submit class:"btn-flat m-3 ml-0 " %>
      <%= link_to "Back to the admin page",  admin_path, class:"btn-flat m-3 mr-0 text-decoration-none" %>
    </div>
  <% end %>
</div>

app/views/yoga_studios/edit.html.erb
<div class="container">
  <div class="mb-3 d-flex justify-content-md-around">
   <div class="form-control bg-white p-5 rounded-4 border-0 shadow-sm">
      <%= simple_form_for(@yoga_studio) do |ys| %>
        <strong><h3 class="mb-4">Edit a yoga studio</h3></strong>
        <%= ys.input :name %>
        <%= ys.input :description %>
        <%= ys.input :address %>
        <%= ys.input :photos, as: :file, input_html: {multiple: true} %>
        <div class="d-flex justify-content-between">
          <%= ys.submit class:"btn-flat m-3 ml-0 " %>
          <%= link_to "Back to all studios",  yoga_studios_path, class:"btn-flat m-3 mr-0 text-decoration-none" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/yoga_studios/new.html.erb
<div class="container">
  <div class="mb-3 d-flex justify-content-md-around">
    <%= render "yoga_studios/form", yoga_studio: @yoga_studio %>
  </div>
</div>

app/views/yoga_studios/show.html.erb
<div class="container">

  <%# first row for info and photo %>
  <div class="show-container d-flex justify-content-between mt-3 flex-grow-1">

    <%# info card %>
    <div class="my-card w-50">
      <h2><%= @yoga_studio.name %></h2>
      <%= render 'shared/average_rating', reviewable_type: @yoga_studio %>
      <p><i class="fa-solid fa-location-dot mt-3"></i> <%= @yoga_studio.address %></p>
      <p class="mt-3 border-top pt-3"><%= @yoga_studio.description %></p>
    </div>
    <%# photo %>

      <% if @yoga_studio.photos.attached? %>
      <%# cl_image_tag @yoga_studio.photos.first.key, class: "rounded shadowed w-50 mb-3", style:"object-fit: cover; object-position: top;" %>
      <%= render 'shared/carousel', yoga_studio: @yoga_studio %>
       <% end %>


  </div>

  <div class="show-map mb-3">
    <div style="width: 100%; height: 100%;"
      class="rounded shadowed"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <%# card for classes %>
  <div class="my-card">
    <h2>Classes</h2>
    <div class="d-flex show-container flex-wrap">
      <% @yoga_studio.yoga_studio_teachers.each do |yoga_studio_relation| %>
        <% yoga_studio_relation.yoga_classes.each do |yoga_class| %>
          <% if yoga_class.photo.attached? %>
            <%= link_to(yoga_class_path(yoga_class), class: "text-decoration-none") do %>
              <div class="display-card rounded" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path yoga_class.photo.key %>')">
                <%= yoga_class.name %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# card for teachers %>
  <div class="my-card mt-3">
    <h2>Teachers</h2>
    <div class="d-flex show-container flex-wrap">
      <% @yoga_studio.yoga_studio_teachers.each do |yoga_studio_relation| %>
        <% if yoga_studio_relation.teacher.photo.attached? %>

          <%= link_to(teacher_path(yoga_studio_relation.teacher), class: "text-decoration-none") do %>
            <div class="display-card rounded" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path yoga_studio_relation.teacher.photo.key %>')">
              <%= yoga_studio_relation.teacher.name %>
            </div>
          <% end %>

        <% end %>

      <% end %>
    </div>
  </div>

  <%# card for reviews %>
  <div class="ratings my-card" data-controller="insert-in-list">
    <h2><strong>Reviews</strong></h3>
    <ul class="list-group mb-3" data-insert-in-list-target="items">
    <% @yoga_studio.reviews.each do |review| %>
      <li class="list-group-item pt-3">

        <%# Displaying the stars: %>
        <%= render 'shared/star_rating', star_rating: review.rating %>

        <div class="review-body d-flex justify-content-between align-items-end">
          <p class="mt-3"><%= review.content %></p>
          <%= link_to "Delete",
          polymorphic_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "btn-delete",
          style: "white-space: nowrap; flex-shrink: 1;"
          %>
        </div>
      </li>
    <% end %>
    </ul>

    <% if user_signed_in? %>
    <h3 class="border-top pt-3 mt-4"><strong>Create a new review:</strong></h3>
    <div class="row">
      <div class="col-xs-4">
         <%= render "reviews/form", reviewable: @yoga_studio, review: @review %>
      </div>
    </div>
    <% end %>
  </div>



</div>