config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :yoga_classes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :show]
  end

  resources :teachers, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studios, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studio_teachers, only: [:create]

  resources :bookings, only: [:index, :destroy]

  resources :reviews, only: [:destroy]
  # resources :bookings, only: [:show]

  # Path for confirmation page after the booking was successful
  get "bookings/:id/confirmation", to: "bookings#confirmation", as: :confirmation
  resources :yoga_classes, only: [:index, :show, :new, :create]
  get "/admin", to: "pages#admin"

  resources :users do
    # Add a custom route for the confirmation action if needed
    get 'confirmation', on: :member
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :yoga_class
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @yoga_class = YogaClass.find(params[:yoga_class_id])
    @booking.yoga_class = @yoga_class
    if @booking.save
      redirect_to yoga_class_booking_path(@yoga_class, @booking)
    else
      redirect_to yoga_class_path(@booking.yoga_class)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @user = @booking.user
  end

  def confirmation
    @booking = Booking.find(params[:id])
    @yoga_classes = [@booking.yoga_class]
    @markers = @yoga_classes.map do |yoga_class|
      {
        lat: yoga_class.yoga_studio_teacher.yoga_studio.latitude,
        lng: yoga_class.yoga_studio_teacher.yoga_studio.longitude,
        info_window_html: render_to_string(partial: "shared/show_window", locals: { yoga_studio: yoga_class.yoga_studio_teacher.yoga_studio }),
        marker_html: render_to_string(partial: "shared/marker")
      }
    end
  end

  def index

    @bookings = Booking.joins(:yoga_class)
                       .where(user: current_user)
                       .where("yoga_classes.start_time > ?", DateTime.now)
                       .order("yoga_classes.start_time ASC")
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :yoga_class_id)
  end
end

app/views/bookings/_credit_card_form.html.erb
<!-- Credit card form -->
<section>
  <div class="row">
    <div class="col-md-8 mb-4">
      <div class="my-card mb-4 rounded">
        <div class="card-header py-3">
        <h2 class="mb-0 pb-3 border-bottom">Biling details</h2>
        </div>
        <div class="card-body">
          <%= simple_form_for(user, as: :user, url: user_path(user), html: { method: :patch }) do |u| %>
          <%= hidden_field_tag "booking_id", @booking.id%>
            <div class="row mb-4">
              <div class="col">
                <%= u.input :first_name %>
              </div>
              <div class="col">
                <%= u.input :last_name %>
              </div>
            </div>
              <%= u.input :company %>
              <%= u.input :address %>
              <%= u.input :phone %>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="checkoutForm1" />
              <label class="form-check-label" for="checkoutForm1">
                Shipping address is the same as my billing address
              </label>
            </div>
            <div class="form-check mb-4">
              <input class="form-check-input" type="checkbox" value="" id="checkoutForm2" checked />
              <label class="form-check-label" for="checkoutForm2">
                Save this information for next time
              </label>
            </div>
            <hr>
              <h5 class="mb-2">Payment</h5>
              <div class="row mb-3">
               <div class="col-3">
                  <img src="https://kamboo-project.ngo/wp-content/uploads/2017/02/stripe_credit-card-logos.png" class="img-fluid" alt="Responsive image">
                </div>
              </div>
              <div class="row mb-4">
                <div class="col">
                  <%= u.input :card_name, label: "Cardholder name"  %>
                </div>
                <div class="col">
                  <%= u.input :card_number, label: "Card number"  %>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-6">
                  <%= u.input :card_cvv, label: "CVV" %>
                </div>
                <div class="col-6">
                  <%= u.input :card_expiration, label: "Expiration date"  %>
                </div>
              </div>
              <div class="row">
                <%= u.button :submit, "Pay Now", class: "btn-flat" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>


    <%# Summary %>
    <div class="col-md-4 mb-4">
      <div class="my-card mb-4 rounded" style="position: sticky !important; top: 100px; !important;">
        <div class="card-header py-3">
          <h2 class="mb-0 pb-3 border-bottom">Summary</h2>
        </div>
       <div class="summary-details">
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-calendar-days"></i> <%= @booking.yoga_class.start_time.strftime("%d of %B, %Y") %></p>
          <p><i class="fa-solid fa-clock"></i> <%= @booking.yoga_class.start_time.strftime("%k:%M") %> - <%= @booking.yoga_class.end_time.strftime("%k:%M") %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-location-dot"></i> <%= @booking.yoga_class.yoga_studio_teacher.yoga_studio.address.split(",").first %></p>
          <p><i class="fa-solid fa-person"></i> <%= @booking.yoga_class.difficulty %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-hourglass-half"></i> <%= @booking.yoga_class.duration_in_minutes %> minutes</p>
          <p><i class="fa-solid fa-star"></i> <%= @booking.yoga_class.style %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-person"></i>  <%= @booking.yoga_class.yoga_studio_teacher.teacher.name %></p>
          <p><i class="fa-solid fa-house"></i> <%= @booking.yoga_class.yoga_studio_teacher.yoga_studio.name %></p>
        </div>
      </div>
      <div class="list-group-item d-flex justify-content-between align-items-center border-top pt-3 mt-3 border-0 px-0 mb-3" style="font-size:24px;">
        <div>
          <strong>Price</strong>
        </div>
        <span><strong><%= sprintf("%.2f", yoga_class.price) %>€</strong></span>
      </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Credit card form -->

app/views/bookings/confirmation.html.erb
<div class="container">
  <div class="my-card">
    <h1 class="border-bottom pb-3 mb-3"><i class="fa-solid fa-circle-check"></i> Your booking was successful.</h1>

    <div class="short-details border-bottom pb-2">
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-calendar-days"></i> <%= @booking.yoga_class.start_time.strftime("%d of %B, %Y") %></p>
          <p><i class="fa-solid fa-clock"></i> <%= @booking.yoga_class.start_time.strftime("%k:%M") %> - <%= @booking.yoga_class.end_time.strftime("%k:%M") %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-location-dot"></i> <%= @booking.yoga_class.yoga_studio_teacher.yoga_studio.address %></p>
          <p><i class="fa-solid fa-person"></i> <%= @booking.yoga_class.difficulty %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-hourglass-half"></i> <%= @booking.yoga_class.duration_in_minutes %> minutes</p>
          <p><i class="fa-solid fa-star"></i> <%= @booking.yoga_class.style %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-person"></i>  <%= @booking.yoga_class.yoga_studio_teacher.teacher.name %></p>
          <p><i class="fa-solid fa-house"></i> <%= @booking.yoga_class.yoga_studio_teacher.yoga_studio.name %></p>
        </div>
      </div>
      <p class="info-text mt-3"><%= @booking.yoga_class.description %></p>
        <div class="show-map mb-3">
          <div style="width: 100%; height: 100%;"
            class="rounded shadowed"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      <%= link_to "Back to all classes", yoga_classes_path, class: "btn-flat d-block w-100" %>
    </div>
  </div>

</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1>All Your Future Bookings:</h1>
  <div class="d-flex justify-content-between flex-wrap">
    <% @bookings.each do |booking| %>
      <div class="my-card w-49">
        <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3">
          <%# add photo of the yoga class %>
          <%= cl_image_tag booking.yoga_class.photo.key, class: "avatar-large" %>
          <h2><%= booking.yoga_class.name %></h2>
          <%= link_to "Cancel booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete" %>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-calendar-days"></i> <%= booking.yoga_class.start_time.strftime("%d of %B, %Y") %></p>
          <p><i class="fa-solid fa-clock"></i> <%= booking.yoga_class.start_time.strftime("%k:%M") %> - <%= booking.yoga_class.end_time.strftime("%k:%M") %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-location-dot"></i> <%= booking.yoga_class.yoga_studio_teacher.yoga_studio.address %></p>
          <p><i class="fa-solid fa-person"></i> <%= booking.yoga_class.difficulty %></p>
        </div>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-hourglass-half"></i> <%= booking.yoga_class.duration_in_minutes %> minutes</p>
          <p><i class="fa-solid fa-star"></i> <%= booking.yoga_class.style %></p>
        </div>
        <div class="d-flex justify-content-between">
            <p><i class="fa-solid fa-person"></i>  <%= booking.yoga_class.yoga_studio_teacher.teacher.name %></p>
            <p><i class="fa-solid fa-house"></i> <%= booking.yoga_class.yoga_studio_teacher.yoga_studio.name %></p>
          </div>
      </div>
    <% end %>
  </div>

</div>

app/views/bookings/show.html.erb
<div class="container">
  <%= render 'bookings/credit_card_form', user: @user, yoga_class: @booking.yoga_class, booking: @booking %>
</div>