config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :yoga_classes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :show]
  end

  resources :teachers, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studios, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studio_teachers, only: [:create]

  resources :bookings, only: [:index, :destroy]

  resources :reviews, only: [:destroy]
  # resources :bookings, only: [:show]

  # Path for confirmation page after the booking was successful
  get "bookings/:id/confirmation", to: "bookings#confirmation", as: :confirmation
  resources :yoga_classes, only: [:index, :show, :new, :create]
  get "/admin", to: "pages#admin"

  resources :users do
    # Add a custom route for the confirmation action if needed
    get 'confirmation', on: :member
  end
end

app/views/shared/_average_rating.html.erb
<% sum = 0 %>
<% reviewable_type.reviews.each do |review| %>
  <% if reviewable_type.reviews.size > 0 %>
    <% sum += review.rating %>
  <% end %>
<% end %>
<% if reviewable_type.reviews.size > 0 %>
  <%= render 'shared/star_rating', star_rating: (sum / reviewable_type.reviews.size).round %>
<% else %>
  <%= render 'shared/star_rating', star_rating: 0 %>
<% end %>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel w-50 mb-3">
  <div class="carousel-inner rounded shadowed h-100 d-flex align-items-center">

    <%# First photo %>
    <div class="carousel-item active">
        <%= cl_image_tag yoga_studio.photos.first.key, class: "carousel w-100" %>
      </div>

    <%# Other photos %>
    <% if yoga_studio.photos.attachments.size >= 2 %>
      <% yoga_studio.photos.drop(1).each do |photo| %>
        <div class="carousel-item">
          <%= cl_image_tag photo.key, class: "carousel w-100" %>
        </div>
      <% end %>
    <% end %>

  </div>

  <%# Next / Previous arrows %>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/shared/_filter_bar.html.erb
<div class="filter-bar border-bottom pb-2 pt-2">
  <div class="container">
    <%= form_tag yoga_classes_path, method: :get, class: "dropdown filters" do %>

    <%# Start of filter bar form %>


      <%# Style %>
      <button class="btn-filter dropdown-toggle" type="button" id="style-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
        <i class="fa-solid fa-star"></i> Style
      </button>
      <div class="dropdown-menu p-3 rounded" aria-labelledby="style-dropdown" data-bs-auto-close="false">
        <%# Dropdown Options %>
        <% %w[Hatha Vinyasa Ashtanga Iyengar Hot Kundalini Restorative Yin Power Anusara Prenatal Postnatal Jivamukti Other].each do |yoga_style| %>
          <div class="form-check">
            <%= check_box_tag "style[]", "#{yoga_style}", params[:style]&.include?("#{yoga_style}"), id: "#{yoga_style}-checkbox", class: "form-check-input" %>
            <%= label_tag "#{yoga_style}-checkbox", "#{yoga_style}", class: "form-check-label", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, onclick: "toggleCheckbox('#{yoga_style}-checkbox'); event.stopPropagation(); return false;" %>
          </div>
        <% end %>
      </div>

      <%# Difficulty %>
      <button class="btn-filter dropdown-toggle" type="button" id="difficulty-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
        <i class="fa-solid fa-person"></i> Difficulty
      </button>

      <div class="dropdown-menu p-3 rounded" aria-labelledby="difficulty-dropdown">

        <%# Dropdown Options %>
        <% ["Beginner", "Intermediate", "Advanced", "All Levels"].each do |difficulty| %>
          <div class="form-check">
            <%= check_box_tag "difficulty[]", "#{difficulty}", params[:difficulty]&.include?("#{difficulty}"), id: "#{difficulty}-checkbox", class: "form-check-input" %>
            <%= label_tag "#{difficulty}-checkbox", "#{difficulty}", class: "form-check-label", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }, onclick: "toggleCheckbox('#{difficulty}-checkbox'); event.stopPropagation(); return false;" %>
          </div>
        <% end %>

      </div>




      <%# Duration %>
      <button class="btn-filter dropdown-toggle" type="button" id="duration-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
        <i class="fa-solid fa-hourglass-half"></i> Duration
      </button>

      <div class="dropdown-menu p-3 rounded" aria-labelledby="duration-dropdown">
        <div class="form-group">
          <%= label_tag "duration-min", "Min Duration (minutes)", class: "form-label" %>
          <%= text_field_tag "duration_min", params[:duration_min], class: "form-control", type: "number", min: 0, step: 1, pattern: "[0-9]*", onkeypress: "return event.charCode >= 48 && event.charCode <= 57"  %>
        </div>
        <div class="form-group">
          <%= label_tag "duration-max", "Max Duration (minutes)", class: "form-label" %>
          <%= text_field_tag "duration_max", params[:duration_max], class: "form-control", type: "number", min: 0, step: 1, pattern: "[0-9]*", onkeypress: "return event.charCode >= 48 && event.charCode <= 57"  %>
        </div>
      </div>




      <%# Price %>
      <button class="btn-filter dropdown-toggle" type="button" id="price-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
        <i class="fa-solid fa-tag"></i> Price
      </button>

      <div class="dropdown-menu p-3" aria-labelledby="price-dropdown">
        <div class="form-group">
          <%= label_tag "price-min", "Min Price (€)", class: "form-label" %>
          <%= text_field_tag "price_min", params[:price_min], class: "form-control", type: "number", min: 0, step: 1, pattern: "[0-9]*", onkeypress: "return event.charCode >= 48 && event.charCode <= 57" %>
        </div>
        <div class="form-group">
          <%= label_tag "price-max", "Max Price (€)", class: "form-label" %>
          <%= text_field_tag "price_max", params[:price_max], class: "form-control", type: "number", min: 0, step: 1, pattern: "[0-9]*", onkeypress: "return event.charCode >= 48 && event.charCode <= 57" %>
        </div>
      </div>

        <%# Date / Time %>
        <button class="btn-filter dropdown-toggle" type="button" id="date-range-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
          <i class="fa-solid fa-calendar-days"></i> Date Range
        </button>

        <div class="dropdown-menu p-3 rounded" aria-labelledby="date-range-dropdown" data-controller="flatpickr">
          <div class="form-group">
            <%= label_tag "start-date", "Start Date", class: "form-label" %>
            <%= text_field_tag "start_date", params[:start_date], class: "form-control flatpickr-input", id: "start-date", data: { flatpickr_target: "startTime" } %>
          </div>
          <div class="form-group">
            <%= label_tag "end-date", "End Date", class: "form-label" %>
            <%= text_field_tag "end_date", params[:end_date], class: "form-control flatpickr-input", id: "end-date", data: { flatpickr_target: "endTime" } %>
          </div>
        </div>

      <%# Distance %>
      <button class="btn-filter dropdown-toggle" type="button" id="distance-dropdown" data-bs-toggle="dropdown" aria-bs-haspopup="true" aria-bs-expanded="false">
        <i class="fa-solid fa-location-dot"></i> Distance
      </button>
      <div class="dropdown-menu p-3" aria-labelledby="distance-dropdown">
        <div class="form-group">
          <%= label_tag "address", "Address", class: "form-label" %>
          <%= text_field_tag "address", params[:address], class: "form-control", type: "text" %>
        </div>
        <div class="form-group">
          <%= label_tag "max_distance", "Max Distance (km)", class: "form-label" %>
          <%= text_field_tag "max_distance", params[:max_distance], class: "form-control", type: "number", min: 0, step: 1, pattern: "[0-9]*", onkeypress: "return event.charCode >= 48 && event.charCode <= 57" %>
        </div>
      </div>



    <%# End of filter bar form %>
    <%= submit_tag "Filter", class: "btn-flat" %>
    <%= link_to "Reset Filters", yoga_classes_path, class: "btn-delete btn-reset" %>
    <% end %>
  </div>
</div>

<script>
function toggleCheckbox(checkboxId) {
  var checkbox = document.getElementById(checkboxId);
  checkbox.checked = !checkbox.checked;
}
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
  <div class="card">
    <div>
      <%= link_to yoga_class, class:"card-img-top card-body" do %>
        <% if yoga_class.photo.attached? %>
         <%= cl_image_tag yoga_class.photo.key, class: "img-map shadow-sm  m-3 bg-white rounded-4" %>
        <% end %>
      <%end%>
      <div class=" border-bottom m-2"> <h4><%= yoga_class.name %></h4></div>
    
        <div class="d-flex justify-content-between align-items-end m-2">
          <p class="m-1"><i class="fa-solid fa-tag"> </i> <%= yoga_class.price %> <i class="fa-solid fa-euro-sign"></i></p>
          <p class="m-1"><i class="fa-solid fa-user-group"></i> <%= (yoga_class.capacity - yoga_class.bookings.size) %> / <%= yoga_class.capacity %> spaces left</p>
        </div>
        <div class="d-flex justify-content-between align-items-end m-2">
          <p class="m-1"><i class="fa-solid fa-person"></i> <%= yoga_class.difficulty %></p>
          <p class="m-1"><i class="fa-solid fa-star"></i> <%= yoga_class.style %></p>
        </div>
      </div>
    </div>
</div>

app/views/shared/_marker.html.erb
<%= image_tag "location.png", height: 30, width: 30, alt: "Logo" %>

app/views/shared/_menue.html.erb
<div class="dropdown">
  <button class="btn btn-login" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa-solid fa-bars" style="color:white !important; font-size: 24px;"></i>
  </button>
  <div class="dropdown-menu rounded" aria-labelledby="dropdownMenuButton" style="left: -75px !important">
     <% if user_signed_in? %>
        <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
        <%= link_to "Admin" , admin_path, class: "dropdown-item"  %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item"  %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
      <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <% if user_signed_in? %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "text-decoration-none btn-login-home btn-login", style: "position: absolute; right: 30px; top: 25px;" %>
              <% else %>
                <%= link_to "Login", new_user_session_path, class: "text-decoration-none btn-login-home btn-login", style: "position: absolute; right: 30px; top: 25px;"%>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "text-decoration-none btn-login-home btn-login", style: "position: absolute; right: 30px; top: 25px;" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "text-decoration-none btn-login-home btn-login", style: "position: absolute; right: 30px; top: 25px;"%>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<li class="list-group-item pt-3">

        <%# Displaying the stars: %>
        <%= render 'shared/star_rating', star_rating: review.rating %>

        <div class="review-body d-flex justify-content-between align-items-end">
          <p class="mt-3"><%= review.content %></p>
          <%= link_to "Delete",
          polymorphic_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "btn-delete",
          style: "white-space: nowrap; flex-shrink: 1;"
          %>
        </div>
      </li>

app/views/shared/_search_bar.html.erb
<%= form_with url: yoga_classes_path, method: :get, class: "d-flex position-relative" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control rounded",
    placeholder: "Search for a yoga class, studio or teacher"
  %>
  <button name="button" type="submit" class="btn position-absolute" style="right: 3px; top: 4px;">
    <i class="fas fa-search d-flex justify-content-center"></i>
  </button>
<% end %>

app/views/shared/_show_window.html.erb
<h5><i class="fa-solid fa-location-dot"></i> <%= yoga_studio.address %></h5>

app/views/shared/_star_rating.html.erb
<span class="gl-star-rating gl-star-rating--ltr" data-star-rating="<%= star_rating %>" style="cursor: default; !important">
          <span class="gl-star-rating--stars s50" role="tooltip" data-rating="<%= star_rating %>" style="cursor: default; !important">
            <span data-index="0" data-value="1" class="<%= star_rating >= 1 ? 'gl-active' : '' %>" style="cursor: default; !important"></span>
            <span data-index="1" data-value="2" class="<%= star_rating >= 2 ? 'gl-active' : '' %>" style="cursor: default; !important"></span>
            <span data-index="2" data-value="3" class="<%= star_rating >= 3 ? 'gl-active' : '' %>" style="cursor: default; !important"></span>
            <span data-index="3" data-value="4" class="<%= star_rating >= 4 ? 'gl-active' : '' %>" style="cursor: default; !important"></span>
            <span data-index="4" data-value="5" class="<%= star_rating >= 5 ? 'gl-active' : '' %>" style="cursor: default; !important"></span>
          </span>
        </span>