config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :yoga_classes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create, :show]
  end

  resources :teachers, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studios, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:create]
  end

  resources :yoga_studio_teachers, only: [:create]

  resources :bookings, only: [:index, :destroy]

  resources :reviews, only: [:destroy]
  # resources :bookings, only: [:show]

  # Path for confirmation page after the booking was successful
  get "bookings/:id/confirmation", to: "bookings#confirmation", as: :confirmation
  resources :yoga_classes, only: [:index, :show, :new, :create]
  get "/admin", to: "pages#admin"

  resources :users do
    # Add a custom route for the confirmation action if needed
    get 'confirmation', on: :member
  end
end

app/views/pages/_testimonials.html.erb
<section class="gradient-custom" style="position: relative !important;" >

  <div class="wave-top wave-fill wave1">
    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
    </svg>
  </div>

  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12">
        <div class="text-center mb-4 pb-2">
          <i class="fas fa-quote-left fa-3x text-white"></i>
        </div>

        <div class="my-card" data-aos="zoom-in">
          <div class="card-body px-4 py-5">
            <!-- Carousel wrapper -->
            <div id="carouselDarkVariant" class="carousel slide carousel-dark" data-bs-ride="carousel">
              <!-- Indicators -->
              <div class="carousel-indicators mb-0">
                <button data-bs-target="#carouselDarkVariant" data-bs-slide-to="0" class="active"
                  aria-current="true" aria-label="Slide 1"></button>
                <button data-bs-target="#carouselDarkVariant" data-bs-slide-to="1"
                  aria-label="Slide 1"></button>
                <button data-bs-target="#carouselDarkVariant" data-bs-slide-to="2"
                  aria-label="Slide 1"></button>
              </div>

              <!-- Inner -->
              <div class="carousel-inner pb-4 pt-4">
                <!-- Single item -->
                <div class="carousel-item active">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://images.pexels.com/photos/3823208/pexels-photo-3823208.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start mx-auto mx-lg-0">
                          <h4 class="mb-4">Sarah Johnson - Experienced Yogi</h4>
                          <p class="mb-0 pb-3" style="height: 136px;">
                            "I've been practicing yoga for years and ZenSpace is hands down the best yoga booking platform out there. The filters make it easy to find a class that fits my needs and schedule. I love that I can quickly book and pay for classes without any hassle. Highly recommend!"
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Single item -->
                <div class="carousel-item">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://images.pexels.com/photos/4051518/pexels-photo-4051518.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start mx-auto mx-lg-0">
                          <h4 class="mb-4">Lisa Cudrow - Beginner Yogi</h4>
                          <p class="mb-0 pb-3">
                            "As a beginner to yoga, I was a bit intimidated to try out classes. But with ZenSpace, I was able to filter for beginner classes and find a studio close to my home. The instructors were welcoming and the atmosphere was so peaceful. I've been going to classes regularly ever since!"
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Single item -->
                <div class="carousel-item">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://images.pexels.com/photos/4056529/pexels-photo-4056529.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start mx-auto mx-lg-0">
                          <h4 class="mb-4">John Smith - Yoga Fanatic</h4>
                          <p class="mb-0 pb-3">
                            "I love using ZenSpace to book my yoga classes. The platform is so user-friendly and the search filters make it easy to find exactly what I'm looking for. I've discovered some amazing yoga studios that I would have never found otherwise. Thank you ZenSpace for making my yoga journey even better!"
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Inner -->

              <!-- Controls -->
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselDarkVariant"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselDarkVariant"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            <!-- Carousel wrapper -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="spacer" style="height: 1px;"></div>
  <div class="wave-bottom wave-fill wave1">
  <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
    </svg>
  </div>

</section>

app/views/pages/admin.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center border-bottom mb-4 pb-3">
    <h1 class="">Admin dashboard</h1>
    <div class="admin-buttons">
      <%= link_to "Create new yoga class", new_yoga_class_path, class: "btn btn-flat m-2" %><%= link_to "Create new teacher", new_teacher_path, class: "btn btn-flat m-2" %><%= link_to "Create new studio", new_yoga_studio_path, class: "btn btn-flat m-2" %>
    </div>
  </div>
  <div class="">
    <nav class="">
      <div class="nav mt-2 mb-2 p-3 nav-pills btn-ghost mb-3" id="nav-tab" role="tablist">
        <button class="nav-link rounded active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Yoga Classes</button>
        <button class="nav-link rounded" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Yoga Studios</button>
        <button class="nav-link rounded" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Teachers</button>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
        <div class="">
          <%# <h4 class="mb-3 my-card"> Your yoga classes </h4> %><%# Creating a card for each yoga class: %>
          <div class="row">
            <%@yoga_classes.each do |yoga_class| %>
              <div class="col-4">
                <div class="my-card" data-controller="collapse">
                  <div class="d-flex flex-column justify-content-between border-bottom pb-3 mb-3">
                    <div class="d-flex justify-content-between align-items-center m-2">
                      <h4><%= yoga_class.name %></h4><%if yoga_class.photo.attached? %><%= cl_image_tag yoga_class.photo.key, class: "avatar-admin", alt: "avatar-admin" %><%end %>
                    </div><%# <div class="admin-buttons"> %><%= link_to "Edit",  edit_yoga_class_path(yoga_class), class: "btn btn-edit mt-2 mb-2" %><%= link_to "Delete", yoga_class_path(yoga_class), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete mt-2 mb-2" %><%# </div> %>
                  </div><button class="btn btn-flat mt-2 mb-2 w-100" type="button" data-action="click-&gt;collapse#infoClick">More information</button>
                  <div class="d-none" data-collapse-target="info" id="collapse-&lt;%=yoga_class.id%&gt;">
                    <div class="m-2 p-2 d-flex flex-column">
                      <div class="d-flex justify-content-between">
                        <div class="class-info">
                          <p><i class="fa-solid fa-calendar-days"></i> <%= yoga_class.start_time.strftime("%d of %B, %Y") %></p>
                          <p><i class="fa-solid fa-clock"></i> <%= yoga_class.start_time.strftime("%k:%M") %> - <%= yoga_class.end_time.strftime("%k:%M") %></p>
                          <p><i class="fa-solid fa-user-group"></i> <%= (yoga_class.capacity - yoga_class.bookings.size) %> out of <%= yoga_class.capacity %> spaces left</p>
                        </div>
                      </div><%# Show participants: %><a class="btn btn-flat m-2" data-action="click-&gt;collapse#buttonClick">Show participants</a>
                      <div class="d-none" data-collapse-target="content">
                        <%if yoga_class.bookings.present? %><%yoga_class.bookings.each do |booking| %>
                        <p class="card m-2 p-2"><%= booking.user.email %></p><%end %><%else %>
                        <p>No participants yet</p><%end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end %>
          </div>
        </div><%# Yoga class card end %>
      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
        <div class="">
          <div class="row">
            <%# <h4 class=" mb-3 my-card d-flex justify-content-center"> Your yoga studios </h4> %><%# Creating a card for each yoga studio: %>
            <%@yoga_studios.each do |yoga_studio| %>
              <div class="col-4">
                <div class="my-card" data-controller="collapse">
                  <div class="d-flex flex-column justify-content-between border-bottom pb-3 mb-3">
                    <div class="d-flex justify-content-between align-items-center m-2">
                      <h4><%= yoga_studio.name %></h4><%if yoga_studio.photos.attached? %><%= cl_image_tag yoga_studio.photos.first.key, class: "avatar-admin", alt: "avatar-admin" %><%end %>
                    </div><%# <div class="admin-buttons"> %><%= link_to "Edit", edit_yoga_studio_path(yoga_studio), class: "btn btn-edit mb-2 mt-2" %><%= link_to "Delete", yoga_studio_path(yoga_studio), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete mt-2 mb-2" %><%# </div> %>
                  </div><button class="btn btn-flat mt-2 mb-2 w-100" type="button" data-action="click-&gt;collapse#infoClick">More information</button>
                  <div class="d-none" data-collapse-target="info" id="collapse-&lt;%=yoga_studio.id%&gt;">
                    <p><i class="fa-solid fa-location-dot"></i> <%= yoga_studio.address %></p><%# @yoga_studio_teacher = YogaStudioTeacher.new(yoga_studio: yoga_studio) %><%= simple_form_for(@yoga_studio_teacher) do |f| %><%= f.input :teacher_id, collection: Teacher.all, label: "Teacher name" %><%= f.hidden_field :yoga_studio_id, value: yoga_studio.id %><%= f.submit "Add teacher to this studio", class: "btn btn-flat" %><%end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div><%# Yoga studio card end %>
      </div>
      <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab" tabindex="0">
        <div class="">
          <div class="row">
            <%# <h4 class="mb-3 my-card d-flex justify-content-center">Your teachers</h4> %>
            <%# Creating a card for each teacher: %>
            <%@teachers.each do |teacher| %>
              <div class="col-4">
                <div class="my-card">
                  <div class="d-flex flex-column justify-content-between border-bottom pb-3 mb-3">
                    <div class="d-flex justify-content-between align-items-center m-2">
                      <h4><%= teacher.name %></h4><%if teacher.photo.attached? %><%= cl_image_tag teacher.photo.key, class: "avatar-admin", alt: "avatar-admin" %><%end %>
                    </div><%# <div class="admin-buttons"> %><%= link_to "Edit", edit_teacher_path(teacher), class: "btn btn-edit m-2" %><%= link_to "Delete", teacher_path(teacher), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-delete m-2" %><%# </div> %>
                  </div>
                  <p><%= truncate(teacher.description, :length => 90) %></p>
                </div>
              </div>
            <%end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Hero -->
<div class="p-5 text-center bg-image rounded-3" style="background-image: url('https://wallpapercave.com/wp/wp3157182.jpg'); height: 100vh; width: 100vw; top: 0px; background-size: cover;">
  <div style="background-color: rgba(0,0,0,0.5); width: 100vw; height: 100vh; position: absolute; top: 0px; left:0px;">
    <!-- Log in button -->

  <div class="d-flex justify-content-between align-items-center">
    <%= image_tag "zenspacewhite.png", class:"img-logo" %>
    <div class="mx-3"><%= render "shared/menue" %></div>
    </div>

    <!-- Log in button -->
      <div class="d-flex justify-content-center align-items-top margin-home h-50">
        <div class="text-light" style="width: 800px;">
          <!-- Slogan text animation -->
          <h1 class="mb-4">Find Your Next <span class="mov"> </span>Yoga Class</h1>
          <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
            <script>
              var typed = new Typed(".mov",{
              strings: [,"Hatha", "Vinyasa", "Ashtanga", "Iyengar", "Hot", "Kundalini", "Restorative", "Yin"],
              typeSpeed: 200,
              backSpeed: 200,
              loop: true
            })
            </script>
          <!-- Slogan text animation -->
          <!-- Search Bar  -->
          <div class="w-75 margin-auto">
            <%= render "shared/search_bar" %>
          </div>
          <!-- Search Bar -->
          <div class="filter-buttons d-flex justify-content-center gap-2 mt-3">
            <%= link_to "All Classes", yoga_classes_path, class: "btn-flat" %>
            <%= link_to "Hatha", yoga_classes_path(style: "Hatha"), class: "btn-flat" %>
            <%= link_to "Vinyasa", yoga_classes_path(style: "Vinyasa"), class: "btn-flat" %>
            <%= link_to "Ashtanga", yoga_classes_path(style: "Ashtanga"), class: "btn-flat" %>
            <%= link_to "Yin", yoga_classes_path(style: "Yin"), class: "btn-flat" %>
            <%= link_to "Hot", yoga_classes_path(style: "Hot"), class: "btn-flat" %>
          </div>

        </div>
      </div>
  </div>
  <div class="wave-bottom wave-fill wave1">
    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
    </svg>
</div>
</div>
<!-- Hero -->
<!-- Most Popular Studios + cards -->

<h2 class="text-center mt-2">Most Popular Yoga Classes</h2>
<div class="cards container text-center p-3">
  <div class="d-flex flex-direction-column justify-content-center space-between-around align-middle m-3">
    <% @random_yoga_classes.each do |yoga_class| %>
      <%= link_to yoga_class, class: "card-product-home m-2 text-decoration-none text-reset" do %>
        <div class="card-product card-product-home align-item-center shadow-sm rounded-4 m-2" data-aos="zoom-in">
          <%#= link_to yoga_class, class: "h-100 " do %>
            <% if yoga_class.photo.attached? %>
              <%= cl_image_tag yoga_class.photo.key, class: "img-home" %>
            <% end %>
          <%# end %>
          <%#= link_to yoga_class, class: "text-decoration-none text-reset" do %>
            <div class="card-body m-2 ">
              <div class="border-bottom ">
                <h5 class="mb-3"><%= yoga_class.name %></h5>
              </div>
              <div class="d-flex justify-content-start m-2">
                <p class="text-start"><i class="fa-solid fa-location-dot"></i> <%= yoga_class.yoga_studio_teacher.yoga_studio.address.split(",").first %></p>
              </div>
              <div class="d-flex justify-content-between m-2">
                <p class=""><i class="fa-solid fa-calendar-days"></i> <%= yoga_class.start_time.strftime("%d of %B, %Y") %></p>
              </div>
              <div class="d-flex justify-content-between m-2">
                <p class=""><i class="fa-solid fa-clock"></i> <%= yoga_class.start_time.strftime("%k:%M") %> - <%= yoga_class.end_time.strftime("%k:%M") %></p>
              </div>
            </div>
          <%# end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<!-- Most Popular Studios section + cards -->

<%= render "testimonials" %>

<h1 class="text-center mb-4">Find a Class Nearby</h1>
<div class="show-map mb-5" data-aos="zoom-in">
  <div style="width: 80%; height: 100%; margin: 0 auto;"
    class="rounded shadowed"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>